@startuml CES Admissions
' uncomment the following line and comment the first to use locally
!include /opt/ArchDoc/BYU-PlantUML/BYU_Context_Map.puml

LAYOUT_WITH_LEGEND()
LAYOUT_TOP_DOWN()
'LAYOUT_LEFT_RIGHT()

title CES Core Admissions System Context\n as of %date("yyyy-MM-dd")

Person(officer,"Officer","Admissions Officer")
Person(applicant,"Applicant","Admissions Applicant")
Bounded_Context(cesAdmissions,"CES Core Admissions","CES Admissions System")

BYUSystem(cashnet, "CashNet", "CashNet credit card processing")
CESSystem(cesIdentity, "CES Identity", "CES Identity System")
CESSystem(cesProfile, "CES Profile", "CES Profile System")
CESSystem(cesEndorsement,"Endorsements","CES Endorsement System")
CESSystem(decisionProcessing,"Decision Processing","Decision Processing System")
External_Entity(testScoreProvider,"Test Score Provider","Test Score Provider")
External_Entity(transcriptProvider,"External Institutions","Transcript Providers")
External_Entity(cesSchools,"CES Schools","CES School Onboarding Processes")


Rel(officer,cesAdmissions,"Monitor Application Status / Configure Application Details")
Rel(cashnet,cesAdmissions,"Process credit card transactions for")
Rel(testScoreProvider,cesProfile,"Provide test scores to")
Rel(transcriptProvider,cesProfile,"Provide transcripts to")
Rel(cesProfile,cesSchools,"Provide transcript/test scores to","REST")
Rel(decisionProcessing,cesSchools,"Provide admit decision to","event/REST")
Rel(cesAdmissions,cesSchools,"Provide applicant details to","REST")

Rel(cesIdentity,cesAdmissions,"Provide identity and authorization services to")
Rel(applicant,cesAdmissions,"Apply for admission via")
Rel(cesAdmissions,applicant,"Provide application status update to","email")
Rel(cesEndorsement,cesAdmissions,"Provides Endorsement Status to","event")
Rel(cesProfile,cesAdmissions,"Provides student owned data to")
Rel(cesProfile,decisionProcessing,"Provides student owned data to","REST")
Rel(cesAdmissions,decisionProcessing,"Provide individual's application data to","REST")
Rel(decisionProcessing,cesAdmissions,"Provide admission decision to","event")

@enduml
